### ISSUE TITLE
doesn't compile

### ISSUE THREAD

**Issue by lee-** [OoliteProject/oolite#139]
compiling on gentoo:

 Compiling file src/Core/Entities/SkyEntity.m ...
In file included from src/Core/MiniZip/ioapi.c:24:0:
src/Core/MiniZip/ioapi.h:127:35: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef voidpf   (ZCALLBACK *open_file_func)      OF((voidpf opaque, const char* filename, int mode));
                                   ^
src/Core/MiniZip/ioapi.h:128:34: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef uLong    (ZCALLBACK *read_file_func)      OF((voidpf opaque, voidpf stream, void* buf, uLong size));
                                  ^
src/Core/MiniZip/ioapi.h:129:35: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef uLong    (ZCALLBACK *write_file_func)     OF((voidpf opaque, voidpf stream, const void* buf, uLong size));
                                   ^
src/Core/MiniZip/ioapi.h:130:33: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef int      (ZCALLBACK *close_file_func)     OF((voidpf opaque, voidpf stream));
                                 ^
src/Core/MiniZip/ioapi.h:131:37: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef int      (ZCALLBACK *testerror_file_func) OF((voidpf opaque, voidpf stream));
                                     ^
src/Core/MiniZip/ioapi.h:133:33: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef long     (ZCALLBACK *tell_file_func)      OF((voidpf opaque, voidpf stream));
                                 ^
src/Core/MiniZip/ioapi.h:134:33: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘OF’
 typedef long     (ZCALLBACK *seek_file_func)      OF((voidpf opaque, voidpf stream, uLong offset, int origin));

... and so on

Forum registration doesn't work, either, I'm not getting the email to confirm account creation.

**Comment by cim--** [comment]
Interesting error. What compiler are you using, and which version of Oolite source?

**Comment by lee-** [comment]
gcc version 4.8.4 (Gentoo 4.8.4 p1.5, pie-0.6.1)

The source is from this repo, latest commit is 1c97d0551b7a91441b9bd6a452e6b56d1bdfe3eb.

**Comment by lee-** [comment]
IIUC:

typedef voidpf   (ZCALLBACK *open_file_func)      OF((voidpf opaque, const char* filename, int mode));

Is (or should be) converted into

typedef voidpf   (*open_file_func)(voidpf opaque, const char* filename, int mode);

as the OF() is defined in deps/Linux-deps/include/zconf.h.  So I changed to:

//typedef voidpf   (ZCALLBACK *open_file_func)      OF((voidpf opaque, const char* filename, int mode));
typedef voidpf   *open_file_func(voidpf opaque, const char* filename, int mode);

and that goes through.  Is that perhaps a bug in gcc (or cpp)?

**Comment by lee-** [comment]
#ifndef OF /* function prototypes */
#  ifdef STDC
#    define OF(args)  args
#  else
#    define OF(args)  ()
#  endif
#endif


Is that intentionally args rather than (args)?

**Comment by lee-** [comment]
It works when I copy the definition of OF() from zconf.h into ioapi.h.  However, then I'm getting:

 Compiling file src/Core/MiniZip/ioapi.c ...
 Compiling file src/Core/MiniZip/unzip.c ...
 Compiling file src/Core/Materials/OOPNGTextureLoader.m ...
src/Core/Materials/OOPNGTextureLoader.m:34:6: error: conflicting types for ‘png_error’
 void png_error(png_structp, png_const_charp) NO_RETURN_FUNC;
      ^
In file included from src/Core/Materials/OOPNGTextureLoader.h:30:0,
                 from src/Core/Materials/OOPNGTextureLoader.m:28:
/usr/include/png.h:1960:45: note: previous declaration of ‘png_error’ was here
 PNG_EXPORTA(102, void, png_error, (png_const_structrp png_ptr,
                                             ^
/usr/share/GNUstep/Makefiles/rules.make:464: recipe for target 'obj.spk.dbg/oolite.obj/OOPNGTextureLoader.m.o' failed

**Comment by lee-** [comment]
I commented out line 34 in src/Core/Materials/OOPNGTextureLoader.m and the compilation finished.

**Comment by kanthoney** [comment]
Finally got a Gentoo system running in a VM.  The problem for the minizip part is that in the gentoo version of zlib.h the OF macro is renamed _Z_OF.

**Comment by kanthoney** [comment]
I've managed to build on Gentoo by taking the following steps:

1) Replacing all occurrences of the `OF` macro in the `src/Core/Minizip` folder with `_Z_OF`
2) Add `-fobjc-exceptions` to the `ADDITIONAL_OBJCFLAGS` on line 55 of `GNUmakefile`
3) Commenting out line 34 of `src/Core/Materials/OOPNGTextureLoader.m` (I tried this on my regular system and that build too, so I'm not sure what this line does.)

I don't know the best way of macroing all that so it works out of the box.  I also haven't actually run the build because, being Gentoo, I'm still building a usable window environment from source.

**Comment by AnotherCommander** [comment]
The Linux dependencies include directory contains zconf.h, zlib.h and zutil.h. Does the build succeed if the compiler is pointed to use these headers rather than the default Gentoo ones? Although it doesn't affect the Windows and Mac builds, I would feel uneasy making changes to the current source just to satisfy one distro, given that it compiles as-is with the Linux nightlies (which are meant to be distribution-independent).

**Comment by kanthoney** [comment]
I tried adding `-Ideps/Linux-deps/include` to the include flags.  This worked on Gentoo, but failed on Debian due to picking up the `png.h` in there.  If I change the includes in the minizip folder to `../../../deps/Linux-deps/include/zlib.h` it still picks up the system zconf.h and fails.

**Comment by AnotherCommander** [comment]
OK. I am not entirely sure what the best way to handle this would be, but in my opinion it is very important to keep the distro-independent build intact. If a way can be found to satisfy also Gentoo, without touching anything else, fine. But this of course raises the question: what happens if e.g. Slackware changes something in their libs tomorrow that affects the build there? Will we have to cater for that too (or any other distro doing their own stuff, for that matter)?

**Comment by KonstantinosSykas** [comment]
I think there is no need to change the GNUmakefile, impacting the debian build, to force Gentoo get the headers from `deps/Linux-deps/include`. Try making one of the **pkg-posix** targets.
Example: `$ make -f Makefile pkg-posix-test`

Just don't make any changes to the build code mechanism till the release is out. ;-)

**Comment by kanthoney** [comment]
It compiles pkg-posix-test (with `-fobjc-exceptions` added and the `png_error` line commented out), but then fails to link because it can't find `libpng14`.

The command `uname -a | awk '{ print $2 }'` is equal to the string `gentoo`.  I guess we could use that as a basis for adding distribution specific tweaks if we want to do that.

**Comment by KonstantinosSykas** [comment]
...are the symbolic links in place by executing `./make_so_links.sh` from within the `deps/[x86, x86_64]/lib_linker` folder?

**Comment by kanthoney** [comment]
I didn't know I had to do that!

I did have a problem with undefined references but those were fixed by installing portaudio.  Now it builds fine.

**Comment by lee-** [comment]
Hold on ;)

I don't understand the first workaround I had to apply, i. e. IIUC, the definiton of the OF() macro is not known to the compiler when it comes to include ioapi.h.  I seem to vaguely remember that definitions from headers included into sources are not known in other headers included into the same source file --- or something like that.  Perhaps that's the problem here.

Isn't this easy to fix?  (I haven't investigated (yet) why the definition isn' known.)  The workaround is easy, and it shouldn't cause any problems when compiling on other distributions.  If it does, add an \#ifdef to see whether the macro is defined or not.


The other problem, with png.h vs. OOPNGTextureLoader.m, might be caused by changes due to different versions.  Perhaps the version can be checked and the (re-)declaration of png_error() in OOPNGTextureLoader.m can be avoided for instances in which it already is declared.

However, is the declaration even necessary in OOPNGTextureLoader.m?  My guess would be that it shouldn't be there in the first place because in any case, it should be declared at a place like png.h.  And as long as the declarations are identical, there is no problem, so probably nobody noticed yet.

**Comment by AnotherCommander** [comment]
@lee Please try building as described by Konstantinos and Kevin above (run ./make_so_links.sh from within the deps/[x86, x86_64]/lib_linker folder and then  make -f Makefile pkg-posix-test) without changing anything in the original source. Does this work for you? You may have to install portaudio for this.

We have been building distro-independent binaries for ages using the current source configuration (and Kevin just did it for Gentoo above) and for this reason I am not very fond of the idea of applying changes just so that it builds natively for a specific distro. If we do it for one, then we may have to do it for all and our resources are limited. Although I am not a Linux maintainer, I would personally prefer to be able to spend time on the game code itself, rather than on each distro's idiosyncrasies.

**Comment by kanthoney** [comment]
The macro is called `OF` in the vanilla zlib source.  Gentoo have decided to rename this `_Z_OF` in their version, I guess to avoid potential symbol clashes.  Oolite uses MiniZip, which assumes that the macro is called `OF` so it fails to compile.

**Comment by KonstantinosSykas** [comment]
@kanthoney You are right being surprised (surprise is a "soft" word, I know) not knowing that "lib_linker" step. The target is to have some instructions in the Linux sub-forum after the release.

**Comment by cim--** [comment]
https://code.google.com/p/fritzing/issues/detail?id=1854 suggests
```
#ifdef _Z_OF
#undef OF
#define OF _Z_OF
#endif
```
as a safe fix. Placed immediately after the include of `zlib.h` in `ioapi.h` should be fine. That should be safe to include in 1.82 and have no effect except on gentoo systems.

It also links to https://bugs.gentoo.org/show_bug.cgi?id=383179 ; it seems we're hardly the first app to have problems with this symbol renaming.

After 1.82 - the whole thing is only required for ancient compilers which wouldn't build Oolite anyway, so we can probably take out the macro usage from our copy of minizip entirely

**Comment by kanthoney** [comment]
That worked - I've pushed out a `gentoo` branch which compiles on both Gentoo and Debian.  The command on Gentoo is `make -f Makefile OBJCFLAGS=-fobjc-exceptions`

**Comment by cim--** [comment]
Fixed in PR #144
