### ISSUE TITLE
Sound.playMusic and launching

### ISSUE THREAD

**Issue by CmdrSvengali** [OoliteProject/oolite#180]
Oolite stops the running music when player launches from a station.

Test:
1. Sound.playMusic("OoliteTheme.ogg")
2. Launch

**Comment by AnotherCommander** [comment]
This appears to be intended behaviour. In PlayerEntity.m, the - (void) leaveDock:(StationEntity *)station method contains the instruction to the shared music controller to stop playing. After trying the result with that instruction removed (which allows the music to continue), I think I personally  prefer it when it stops.

Having said that, I guess an option to make this behaviour user selectable could be a possibility.

**Comment by CmdrSvengali** [comment]
But on docking the music continues if the player docks on its own or uses the fast docking option, but not if iTunes or autopilot is used. I've also seen that the handler playerStartedAutoPilot is fired before Oolite starts its autopilot/docking music. Maybe the handler could be called a bit later?

**Comment by AnotherCommander** [comment]
On docking by autopilot, whatever music is being played at the thime has to stop for the Blue Danube to start. Then the Blue Danube stops playing when docking is complete, like it has always been the case since the 8-bit Elites. This is a normal docking events sequence. Now, if the player docks manually or by fast-dock, then whatever music could be playing at that time is probably scripted and, as such, it is left playing. Should one wish to stop a song that is playing, they could do so by scripting.

As for the handler firing before the music starts on docking, could you please describe what it is that you are trying to do that cannot be done already? At the moment, I can't see a problem with moving it a few lines up, but generally I am not too keen changing things that seem to work, unless there is a valid reason.

**Comment by CmdrSvengali** [comment]
Yes, Nikos. The way Oolite works is clear. I only think that we could think about more consistent ways, but I'm absolutely ok with it as it is.

About the handler. What I'm trying to do is to play a different song when the autopilot is triggered. Currently a script has to use a one-shot timer to overrule Oolites BlueDanube. If Oolites Music is started before the handler gets fired it wouldn't need a Timer, if I understand it right. The whole mechanism is for a new library that handles event driven music without the complexity of CCL_Music.js. But establishing streams is costly, so I'm aiming for a simple script (as far as possible).

**Comment by AnotherCommander** [comment]
OK, done. Please test if it helps with what you want to do and wjhether it causes any side effects or not.

**Comment by CmdrSvengali** [comment]
Muchas gracias, looks good, a_c .-) Haven't noticed any strange behaviour yet, but probably we should wait a bit before closing. If you want to see on your own -> https://app.box.com/s/h9qnmebf7zv96cjr5d90brno3tevwr95.

**Comment by AnotherCommander** [comment]
Olli, this is beautiful. Already installed in the standard OXPs folder here. You should really announce it on the forum, it is an amazing demo.

And, so as to not drift away from topic too much, rhe issue remains open for the moment, pending confirmation of good functionality following a sufficient testing period.

**Comment by CmdrSvengali** [comment]
Still haven't seen a problem and also tried it with Frame's Random Docking Music. Just as sidenote - is Sound.playMusic excluded from the timelimiter?

The demo is ok, but still needs some tweaks. Most of the other parts are undertested and may change anytime. It will take some more time before I can announce anything.

**Comment by AnotherCommander** [comment]
I think this issue would now be good to close?

**Comment by CmdrSvengali** [comment]
Yes, Nikos. And muchas gracias.-)
