### ISSUE TITLE
Gamma setting affects entire operating system rather than just the game window

### ISSUE THREAD

**Issue by Moth-Tolias** [OoliteProject/oolite#196]
using windows 7, oolite v 1.82.

**Comment by AnotherCommander** [comment]
This is a known issue and is due to the way SDL implements gamma. We cannot fix it without affecting code portability, as we would need to separate the Windows and Linux code paths (and we will not fix it, at least not for 1.84). 

In any case, the system gamma returns to normal once the game has exited.
