### ISSUE TITLE
Fails to start 

### ISSUE THREAD

**Issue by kcallis** [OoliteProject/oolite#199]
I am using Oolite 1.82 on a Latitude Dell 6420 with Nvidia GF119M [NVS 4200M] and 8 GB of RAM running under Linux Mint 18.2. I am probably guilty of loading a ton of Add-Ons, but I have never had an issue with the app dying upon closing

```
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (XFree86-VidModeExtension)
  Minor opcode of failed request:  10 (XF86VidModeSwitchToMode)
  Value in failed request:  0x2dc
  Serial number of failed request:  179
  Current serial number in output stream:  181
AL lib: (EE) alc_cleanup: 1 device not closed
Inconsistency detected by ld.so: dl-close.c: 811: _dl_close: Assertion `map->l_init_called' failed!

Erk. It looks like Oolite died with an error. When making an error
report, please copy + paste the log above into the report.
```

**Comment by KonstantinosSykas** [comment]
Hi kcallis.

this is most probably a gfx driver issue, check a relevant thread at our Bulletin Board [here](http://aegidian.org/bb/viewtopic.php?p=231038#p231038).

However, please, let us know if you are using the Oolite package from the Linux repository or from [oolite.org](http://oolite.org).

Please, also share the `~/.Oolite/Logs/Latest.log`.

**Comment by AnotherCommander** [comment]
No response received on this issue for a few months now. Does it occur also with 1.84?

**Comment by AnotherCommander** [comment]
No response received. Issue closed.

**Comment by csiga777** [comment]
Hi,
I have the same 151 error message. I played for xxx hours and it worked fine, exited for a nap, and now this error. No updates or restart or any change tot the system. I did a restart finally because of the xx day uptime, it didn't help. Thanks for any advice in advance. This is a cool game I wanted to play since the 80s. Here is my latest.log:

Opening log for Oolite version 1.90 (x86-64) under Linux 4.15.0-124-generic at 2020-12-02 21:33:10 +0100.
Intel(R) Core(TM)2 Duo CPU     E7300  @ 2.66GHz 2 processors detected.
Build options: OpenAL, new planets.

Note that the contents of the log file can be adjusted by editing logcontrol.plist.

21:33:10.586 [dataCache.rebuild.datesChanged]: Cache is stale (modification dates have changed). Rebuilding from scratch.
21:33:10.888 [display.mode.list.native]: X11 native resolution detected: 2432 x 1024
21:33:10.992 [joystick.init]: Number of joysticks detected: 0
21:33:10.993 [rendering.opengl.version]: OpenGL renderer version: 3.3.0 ("3.3.0 NVIDIA 340.108"). Vendor: "NVIDIA Corporation". Renderer: "GeForce 9600 GT/PCIe/SSE2".
21:33:10.993 [rendering.opengl.extensions]: OpenGL extensions (238):
GL_ARB_draw_instanced, GL_NV_float_buffer, GL_ARB_occlusion_query, GL_EXT_texture_env_add, GL_ARB_texture_storage, GL_ARB_texture_env_dot3, GL_ARB_sync, GL_EXTX_framebuffer_mixed_formats, GL_ARB_texture_multisample, GL_ARB_explicit_uniform_location, GL_NV_texture_env_combine4, GL_ARB_point_parameters, GL_ARB_vertex_array_object, GL_NVX_gpu_memory_info, GL_NV_vertex_buffer_unified_memory, GL_ARB_blend_func_extended, GL_NV_explicit_multisample, GL_EXT_provoking_vertex, GL_NV_texture_shader2, GL_EXT_blend_equation_separate, GL_ARB_compressed_texture_pixel_storage, GL_NV_texture_shader3, GL_ARB_texture_stencil8, GL_ARB_texture_non_power_of_two, GL_ARB_texture_mirrored_repeat, GL_ARB_debug_output, GL_EXT_multi_draw_arrays, GL_NV_fence, GL_ARB_timer_query, GL_ARB_texture_buffer_object, GL_ARB_texture_buffer_range, GL_NV_occlusion_query, GL_EXT_abgr, GL_ARB_vertex_program, GL_NV_shader_buffer_load, GL_ATI_texture_float, GL_ARB_viewport_array, GL_KTX_buffer_region, GL_ARB_shadow, GL_NV_light_max_exponent, GL_EXT_texture_cube_map, GL_EXT_texture_compression_dxt1, GL_NV_texture_multisample, GL_NV_primitive_restart, GL_EXT_framebuffer_object, GL_EXT_texture_sRGB, GL_ARB_conservative_depth, GL_ARB_get_program_binary, GL_ARB_multitexture, GL_NV_half_float, GL_NV_copy_image, GL_NV_path_rendering, GL_NV_register_combiners, GL_EXT_texture_compression_rgtc, GL_ARB_shader_objects, GL_EXT_blend_func_separate, GL_EXT_bgra, GL_ARB_pixel_buffer_object, GL_NV_fragment_program2, GL_EXT_Cg_shader, GL_ARB_draw_buffers, GL_EXT_separate_shader_objects, GL_NV_texgen_reflection, GL_ARB_texture_env_crossbar, GL_ARB_fragment_shader, GL_EXT_texture_swizzle, GL_EXT_fog_coord, GL_EXT_vertex_array_bgra, GL_EXT_framebuffer_blit, GL_NV_copy_depth_to_color, GL_ARB_texture_compression_rgtc, GL_NV_vertex_program1_1, GL_ARB_seamless_cube_map, GL_EXT_texture_shared_exponent, GL_ARB_shading_language_420pack, GL_EXT_geometry_shader4, GL_EXT_direct_state_access, GL_EXT_compiled_vertex_array, GL_NV_parameter_buffer_object2, GL_KHR_debug, GL_ARB_copy_image, GL_NV_vertex_array_range2, GL_ARB_shading_language_include, GL_EXT_texture_storage, GL_EXT_separate_specular_color, GL_ARB_vertex_type_2_10_10_10_rev, GL_NV_vdpau_interop, GL_EXT_vertex_array, GL_ARB_shading_language_100, GL_EXT_framebuffer_multisample_blit_scaled, GL_EXT_rescale_normal, GL_ARB_texture_float, GL_EXT_packed_depth_stencil, GL_EXT_bindable_uniform, GL_ARB_texture_swizzle, GL_ARB_half_float_pixel, GL_EXT_texture_compression_s3tc, GL_EXT_draw_instanced, GL_ARB_occlusion_query2, GL_NV_transform_feedback, GL_NV_texture_compression_vtc, GL_ARB_texture_rgb10_a2ui, GL_SGIS_texture_lod, GL_ARB_geometry_shader4, GL_NV_point_sprite, GL_ARB_framebuffer_object, GL_NV_conditional_render, GL_EXT_stencil_two_side, GL_ARB_texture_rg, GL_NV_texture_expand_normal, GL_ARB_color_buffer_float, GL_NV_framebuffer_multisample_coverage, GL_EXT_blend_color, GL_NV_packed_depth_stencil, GL_NV_geometry_shader4, GL_NV_texture_rectangle, GL_ARB_vertex_array_bgra, GL_EXT_texture_integer, GL_EXT_texture_array, GL_ARB_base_instance, GL_EXT_import_sync_object, GL_ARB_shading_language_packing, GL_ARB_fragment_program_shadow, GL_ARB_fragment_layer_viewport, GL_NV_gpu_program4, GL_EXT_texture_buffer_object, GL_NV_vertex_program2_option, GL_ARB_map_buffer_range, GL_ARB_fragment_program, GL_ARB_copy_buffer, GL_S3_s3tc, GL_NV_depth_clamp, GL_EXT_texture_lod_bias, GL_EXT_texture_filter_anisotropic, GL_EXT_draw_buffers2, GL_NV_fragment_program, GL_EXT_secondary_color, GL_ARB_ES3_compatibility, GL_EXT_framebuffer_multisample, GL_ARB_window_pos, GL_IBM_rasterpos_clip, GL_EXT_texture_env_combine, GL_ARB_vertex_shader, GL_SGIS_generate_mipmap, GL_ARB_compatibility, GL_ATI_texture_mirror_once, GL_EXT_packed_float, GL_ARB_texture_border_clamp, GL_ARB_explicit_attrib_location, GL_NV_blend_square, GL_ARB_internalformat_query, GL_EXT_texture3D, GL_ARB_arrays_of_arrays, GL_SUN_slice_accum, GL_ARB_robust_buffer_access_behavior, GL_NV_vertex_array_range, GL_ARB_ES2_compatibility, GL_NV_vertex_program, GL_NV_multisample_filter_hint, GL_ARB_invalidate_subdata, GL_EXT_texture_mirror_clamp, GL_EXT_texture_sRGB_decode, GL_ARB_texture_compression, GL_NV_vertex_program2, GL_NV_multisample_coverage, GL_ARB_texture_env_add, GL_ARB_imaging, GL_NV_vertex_program3, GL_ARB_provoking_vertex, GL_ARB_framebuffer_no_attachments, GL_EXT_gpu_shader4, GL_ARB_texture_rectangle, GL_EXT_texture_edge_clamp, GL_ARB_draw_elements_base_vertex, GL_ARB_fragment_coord_conventions, GL_ARB_separate_shader_objects, GL_SGIX_shadow, GL_ARB_texture_cube_map, GL_NV_ES1_1_compatibility, GL_ARB_vertex_attrib_binding, GL_EXT_framebuffer_sRGB, GL_ARB_clear_buffer_object, GL_NV_fragment_program_option, GL_EXT_texture_compression_latc, GL_ARB_vertex_type_10f_11f_11f_rev, GL_ARB_robustness, GL_ARB_point_sprite, GL_ARB_internalformat_query2, GL_NV_depth_buffer_float, GL_ARB_depth_texture, GL_EXT_texture_object, GL_EXT_depth_bounds_test, GL_NV_fog_distance, GL_ARB_instanced_arrays, GL_EXT_blend_minmax, GL_SGIX_depth_texture, GL_ATI_draw_buffers, GL_ARB_enhanced_layouts, GL_ARB_multi_bind, GL_ARB_framebuffer_sRGB, GL_EXT_shader_integer_mix, GL_EXT_blend_subtract, GL_NV_register_combiners2, GL_EXT_packed_pixels, GL_IBM_texture_mirrored_repeat, GL_NV_texture_shader, GL_EXT_draw_range_elements, GL_ARB_texture_mirror_clamp_to_edge, GL_ARB_sampler_objects, GL_ARB_half_float_vertex, GL_ARB_depth_clamp, GL_ARB_texture_storage_multisample, GL_ARB_transpose_matrix, GL_NV_parameter_buffer_object, GL_ARB_vertex_buffer_object, GL_ARB_texture_query_levels, GL_EXT_pixel_buffer_object, GL_ARB_texture_view, GL_NVX_conditional_render, GL_ARB_texture_env_combine, GL_ARB_shader_bit_encoding, GL_EXT_timer_query, GL_EXT_gpu_program_parameters, GL_ARB_shader_texture_lod, GL_ARB_program_interface_query, GL_ARB_uniform_buffer_object, GL_ARB_multisample, GL_EXT_texture_env_dot3, GL_EXT_shadow_funcs, GL_ARB_stencil_texturing, GL_EXT_texture_lod, GL_ARB_depth_buffer_float, GL_NV_pixel_data_range, GL_ARB_map_buffer_alignment, GL_EXT_stencil_wrap, GL_EXT_x11_sync_object, GL_EXT_point_parameters, GL_NV_texture_barrier
21:33:11.003 [rendering.opengl.shader.support]: Shaders are supported.
21:33:11.250 [dataCache.rebuild.datesChanged]: Cache is stale (modification dates have changed). Rebuilding from scratch.
21:33:11.250 [searchPaths.dumpAll]: Resource paths: 
    ~/GNUstep/Applications/Oolite/oolite.app/Resources
    AddOns
21:33:11.400 [shipData.load.begin]: Loading ship data.
21:33:12.189 [script.javascript.init]: JavaScript reset successful.

Closing log at 2020-12-02 21:33:12 +0100.

**Comment by csiga777** [comment]
Solved! I didn`t exit fullscreen mode the last time i played, and when I restarted oolite, the resolution didn`t fit. I don`t know if this is to be considered as a bug. Not many people use CRTs and change resos from native nowadays, I do it for the 200/+Hz experience... This Sony 24" eats 1600x1200 in 120Hz, 800x600 in 300Hz... I just can`t get a replacement for this.

Seems like Oolite doesn`t change to higher resolution when it starts up in fullscreen mode. It would be cool to be able to use the mouse in window, but that`s another thing...
