### ISSUE TITLE
Native exception: player.ship.price

### ISSUE THREAD

**Issue by CmdrSvengali** [OoliteProject/oolite#203]
Using player.ship.price inflight raises an exception. See #115
This limits the use of the debug console (and I think developers will need to inspect the entities).

Exception: Error: Native exception: src/Core/Entities/PlayerEntity.m:855  Assertion failed in PlayerEntity(instance), method commanderDataDictionary.  Cannot create commander data dictionary unless docked.
    Active script: oolite-debug-console 1.84
    oolite-debug-console.js, line 341:
      var propVal = value[key];

**Comment by AnotherCommander** [comment]
But... but this is my way of testing that native exceptions work! :-)

This is an assert hit and it looks to have been put there deliberately. Not sure what happens if it simply gets removed (will test once I get a chance), but I guess that if it's there, it is for a good reason.  A possible workaround might be to check when player.ship.price is executed from a script or the console and output an error message right there, rather than letting the code run (and trying to create a commander dictionary, which is what leads to the assert being hit), if the player is found to be undocked.

**Comment by CmdrSvengali** [comment]
Ah, ok, I see ... a working test, indeed .-)

Why not simply returning 0 (zero) or null when inflight and add a comment to the documentation?

**Comment by AnotherCommander** [comment]
Based on the comments by @cim on issue #115, I have committed a possible fix for this problem. It seems to work OK for me and I can now execute player.ship.price while in flight, as well as `:d PS` from the debug console (another one which was throwing an exception when executed while not docked) without any apparent issues. @CmdrSvengali, please test and let us know if OK to close this.

**Comment by CmdrSvengali** [comment]
Looks good for me - thanks a lot, Nikos. You are my hero!

**Comment by AnotherCommander** [comment]
Thanks :-) Issue closed then.
