### ISSUE TITLE
Renaming Lave in planetinfo.plist and oolite behaves oddly.

### ISSUE THREAD

**Issue by DTHP** [OoliteProject/oolite#215]
I used Name = "SOL"; for "0 7" in a planetinfo.plist
And the game starts to behave oddly.

I then pick new game
first of all, the start screen shows with nothing but the Equipment, there is no market or shipyard as if the mainstation does not exist. When i launch there is only the Sun and I can use the Torus drive to get out of a sphere of nebulas (skybox i presume). The main planet is presumably inside the sun. because that is where the compass points.

**Comment by AnotherCommander** [comment]
Due to the change of name of system that the standard start-up scenario uses, the game was failing to set up the current and target systems properly. We are now fall back to reading the system coordinates from the savefile in order to set up our systems, if the ID of the system calculated from the name in the savefile returns -1 for whatever reason. Please test the committed fix and confirm if OK to close.

**Comment by AnotherCommander** [comment]
After some further own testing, it seems that renaming the scenario start up planet does not cause any obvious problems anymore. I believe this bug can be therefore considered resolved, Closing issue,
