### ISSUE TITLE
Last nightly build missing Linux 64-bit

### ISSUE THREAD

**Issue by gilbertohasnofb** [OoliteProject/oolite#252]
Just a heads up, but the last nightly build Oolite Nightly Build (2017-07-29) `oolite-trunk-1.85.0.8e192e0` is missing the Linux 64-bit.

**Comment by AnotherCommander** [comment]
Although the build was not sent to github for some reason, it seems that it was generated by our buildbot and is available for download here: http://terrastorage.no-ip.info/oolite/status_AMD64.html

**Comment by gilbertohasnofb** [comment]
Great, thanks. I will keep an eye if the next nightly release will also have this issue or not.

**Comment by KonstantinosSykas** [comment]
Github has been manually updated with Linux 64-bit nightly build. For some reason, or another, the nightly publishing system did not detect the Linux 64-bit that was produced in terrastorage. I am still looking into it. If I don't come up with anything I'll close this case.

**Comment by KonstantinosSykas** [comment]
My analysis gives the following story.

**29.07**: The Linux 64bit VM freezes during boot. *(this happens from time to time but I usually notice it :flushed:)*
**30-31.07**: The Linux 64bit VM cannot start because the previous session is still running.
**31.07**: Following to O/S maintenance operations, I restart the server (without ever noticing that a VM was frozen) :man_facepalming:   
**01.08**: The Linux 64bit VM starts (without any other VM session blocking it anymore) detecting that a new nightly must be built. Even though TerraStorage and Google Drive public repositories were synced with the new nightly, the Github release was not updated; such functionality is not yet supported by our built mechanism.

I think it is safe to proceed and close this case now. 
Thank you @gilbertohasnofb !

**Comment by gilbertohasnofb** [comment]
> I think it is safe to proceed and close this case now.

Great, thanks for the quick solution!
