### ISSUE TITLE
Ambience Collection doesn't recognise System Features: Rings

### ISSUE THREAD

**Issue by Fleurghber** [OoliteProject/oolite#258]
Doesn't seem to be a problem with the computer, as rings are displayed normally.  Any suggestions?

**Comment by gilbertohasnofb** [comment]
I believe Ambience Collection needs to be updated as when I released the new version of the rings (starting with version 2.0) I have also modified the OXP identifier to `cim.gsagostinho.systemfeatures.rings` (in hindsight I perhaps should have kept the original one). I think Norby is the person responsible for the Ambience Collection OXP, would you mind dropping him a PM in the forum so that he gets to know this?

**Comment by Norbylite** [comment]
Thank you for the report, Ambience Collection is updated now.

**Comment by gilbertohasnofb** [comment]
@Norbylite Great, many thanks. Apologies for not thinking about compatibility issues, I was very new to the world of OXP development  when I first modified those rings.

**Comment by Norbylite** [comment]
No problem, we all was new once. ;)

**Comment by AnotherCommander** [comment]
So, it looks like we can go ahead and close this now.
