### ISSUE TITLE
Apparently defective Config/effectdata.plist files

### ISSUE THREAD

**Issue by Fleurghber** [OoliteProject/oolite#261]
oolite.oxp.Norby.Andromeda.oxz

**Comment by AnotherCommander** [comment]
I will have to close this issue because it is not referring to any core game problem.

Please note that the github issue tracker for Oolite is for reporting issues found in the core game only. We do not follow or track OXP/OXZ status. For this, you will have to use the forum and report each of the problems found in the corresponding threads for the OXP/OXZ you are flagging. The person(s) responsible for the status of each OXP/OXZ is/are the OXP/OXZ's developers and not the core game crew.

If during the the course of an OXP problem investigation it turns out that it is, in fact, a core game issue, then you can open a bug report for it here and we will take a look at it.
