### ISSUE TITLE
Port away from outdated Mozilla JavaScript engine

### ISSUE THREAD

**Issue by jbicha** [OoliteProject/oolite#271]
oolite uses the SpiderMonkey JavaScript engine from Firefox 4 (mozjs1.8.5). That is very outdated.

Because of this, oolite has been removed from [Debian](https://tracker.debian.org/pkg/oolite) Testing and will probably be removed from [Ubuntu](https://launchpad.net/bugs/1728038) 18.04 LTS Alpha soon.

Ideally, oolite would be ported to work with the currently supported mozjs52 (official release is still pending but it is available in any GNOME 3.26 Linux distribution).

**Comment by jbicha** [comment]
One [project](https://github.com/CMB/edbrowse) switched to the [duktape](http://duktape.org/) JavaScript engine.

**Comment by AnotherCommander** [comment]
Sorry to say that, from my point of view, this issue is not planned to be addressed any time soon.

Porting away from mozjs 1.8.5 presents us with all sort of problems. Oolite is not just a Linux project, it is a multi-platform one and everything that we do (or don't do) has to take that fact into account. In this case, the biggest problem that we are faced with is Windows support.

Building 1.8.5 for Windows has been one of the hardest tasks I've had to take on since I got involved with the project ten years ago. When I did that, mingw support for Spidermonkey was not a thing (VS support ony at that time). I do not know what kind of support exists for that right now, but I really do not have the time or inclination to go and find out at this point.

What we have right now works and has been tested for many years on all three supported platforms. A significant number of OXPs have been written based on the API provided by 1.8.5. Mozilla releases new versions too frequently, often with heavy changes to their API and interfacing with applicaitons making use of it. We already know that the current JS API is very different to what we use in the Oolite core. We cannot expect to be able to stand behind that; the Oolite team is simply too small to be able to do it. With the compiler used currently for Winows (gcc 4.7.1 and there are reasons we cannot go to newer gcc versions right now), I am not even  sure a build of the latest mozjs is even possible. 

As I have mentioned a bunch of times already, I would prefer to work on Oolite's code rather than maintaining its libraries. This is why we have selected a fixed set of external library versions that we know work for us and concentrate on building the game around them. Changing the current version of a library can happen in certain cases, but only when it is absolutely required or when the benefits warrant the time invested in doing it. In the case of libmozjs I cannot see why any of the dev team members should spend huge amounts of time (because no less than huge is the expectation here) to achieve... exactly what? The same functionality we already have?  For a result that cannot be guaranteed and that, even if successful, would most likely require major rewrites of existing expansion packs just to be able for them to continue working?

Apologies if I sound strongly dismissing of the idea. The points raised  above are my own personal opinion and do not necessarily reflect or represent the opinions of other members of the team. In closing, I would just want to say that it is sad to see the game being pulled off repositories because of libmozjs, but at least Linux users still have the option of downloading the latest - and fully supported - Linux version of the game from www.oolite.org, which is specifically designed to a) work on all Linux systems, regardless of distro and b) not interfere with any already installed libraries in the system. Oolite for Linux creates its own isolated ecosystem when running and does not see or change anything outside of that. If you already have a recent libmozjs installed, you can still run Oolite with its own, outdated 1.8.5 and it will not affect your system in any way. Given the removal of the game from certain repositories, I think that this fact is something that should be stressed and emphasized: The latest version of Oolite can _still_ run fine on Linux.

**Comment by jbicha** [comment]
The problem isn't that mozjs185 is old, the problem is that it hasn't received any security updates in, I believe, 6 years.

As a workaround, I recommend you look into [Snap](https://snapcraft.io/) and/or [Flatpak](https://flatpak.org/) to make your software available on Linux distros that don't offer the required library versions.

**Comment by KonstantinosSykas** [comment]
> As a workaround ... to make your software available on Linux distros that don't offer the required library versions.

Actually Oolite for Linux is already offering a cross-distribution Linux installer and this is done since the time the Linux port was made.

Some 6 years ago we moved from the [Autopackage](https://en.wikipedia.org/wiki/Autopackage) multi-distribution binary packaging framework to Stephane Peter's [makeself.sh](http://makeself.io/). 

This is just a shell script that generates a self-extractable compressed tar archive from a directory. It is open source and sticks to the KISS principle, while making an installer with the following characteristics (and I'm mostly quoting [Flatpak design goals](http://docs.flatpak.org/en/latest/introduction.html) here):
> Allow Oolite to be installed on any Linux distribution
> Provide consistent environments for Oolite, to facilitate testing and reduce bugs.
> Decouple Oolite from the operating system, so that Oolite doesn’t depend on specific versions of each distribution.
> Allow Oolite to bundle its own dependencies, so that it can use libraries that aren’t provided by a Linux distribution, and so it can depend on specific versions or even patched versions of a library.

Snap or any other repository based packager should be considered to expand the Oolite for Linux delivery points and a call for maintainers on that matter will be soon posted in the Oolite-Linux forum hosted in the Oolite Bulletins Board.

**Comment by AnotherCommander** [comment]
Unless there are further comments on this issue, I would like to go ahead and close it with the "Will Not Fix" resolutioin soon.

**Comment by AnotherCommander** [comment]
Issue closed. Will Not Fix.

**Comment by petterreinholdtsen** [comment]
For the record, oolite is now removed from Debian, see <URL: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886102 > and https://tracker.debian.org/pkg/oolite .
