### ISSUE TITLE
Building on OSX - older code circa 2014

### ISSUE THREAD

**Issue by submersibletoaster** [OoliteProject/oolite#291]
I am attempting to revive an old branch 'shady-atmos'. A merge of some 1000+ commits from master and a bit of conflict resolution gets me to a point where it builds and runs on OSX using
`xcodebuild -scheme "Oolite - Debug"  build`

however when trying to build the tip of the branch shady-atmos/349d99f I receive this error

`xcodebuild: error: Failed to build project Oolite with scheme Oolite - Debug.
	Reason: The run destination My Mac is not valid for Running the scheme 'Oolite - Debug'`

Previously (2014) I was building this on linux and must admit to being not very xcode savvy.

Any suggestions would be helpful.

**Comment by jobi-wan** [comment]
SDKROOT is set to macos10.8 in that commit
Make sure you have MacOSX10.8.sdk in your xcode.
(Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/)

I just tried it and I don't have the same issue. (I do have MacOSX10.8.sdk installed.) 

In order to make that commit compile on OSX10.10.5, xcode 7.1 (7B91b), I had to ...
- remove -Werror=all and -Werror=extra from oolite-warnings.xcconfig
- add CLANG_LINK_OBJC_RUNTIME = NO to oolite-targets.xcconfig
- remove CLANG_ENABLE_OBJC_ARC = YES from build settings for Oolite-importer in Mac Specific

**Comment by submersibletoaster** [comment]
Thank you for this @jobi-wan  - that got xcodebuild running again, after I set the MinimumSDKVersion for xcode in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist.

I'm still having issues with building deps but those I have a chance of fixing on my own. Cheers
