### ISSUE TITLE
Enable HUD toggle during gameplay

### ISSUE THREAD

**Issue by clintmoyer** [OoliteProject/oolite#322]
The ability to toggle the HUD is currently only available as a [Debugging Key](http://wiki.alioth.net/index.php/Oolite_Keyboard_Controls#Debugging_Keys) when the game is paused. It seems to serve a greater purpose than the rest of the debug keys, and could be useful in general for a greater field of view during regular gameplay, as well as improved screen capturing.

Let me know if I am off on this, but I can see it being a more general feature rather than a debug key.

**Comment by AnotherCommander** [comment]
I am a bit concerned with OXPs that control HUD on/off switching. The way it is now, such OXPs can have a purpose. Making HUD on/off a direct user control will eliminate that. From a strict gameplay point of view, there is no apparent reason why the HUD would be deliberately turned off. Additionally, the field of view is not dependent on HUD being on or off so I cannot see the benefit of the change.

I am not completely against the idea - which is helped by the changes required being trivial,  just not sure why it would be better than the current status,

**Comment by clintmoyer** [comment]
My initial thoughts were really that the HUD takes up a lot of screen space, and this gives users a big chunk of space back in the case of screen-shotting. The alternative being to switch views, but it is not always the perspective change being desired. I'd say this can be closed then until a future need brings it back up. Agree that it may not be needed.

**Comment by AnotherCommander** [comment]
Leaving this open for a day more or so, in case someone else would like to contribute their opinion. The idea is not entirely without merit and it might be an interesting topic for discussion in the forum, where it will probably get more visibility.

**Comment by phkb** [comment]
I had a couple of thoughts about this. On the positive side, this PR would make it a lot easier to turn the HUD off, and the code change is quite trivial. It would also make it much easier to map the function to a joystick command. On the neutral side, there would not likely be any improvement for screen capturing, because if you're taking a screenshot, the first thing you will probably do is pause the game. So, pause, hide HUD, screenshot, or hide HUD, pause, screenshot, there is no real gain here. 
As for getting screen space back, I'd probably call that a line ball. Some HUD's (like the "Dangerous" HUD), block part of the screen to simulate a cockpit view. If you like that sort of thing, why would you need to turn the HUD off again? If screen real-estate means so much to you, you would probably use one of the HUD's out there that give you a large field of view anyway. Having the ability to use one instead of two keys to turn off the HUD is a nice-to have, I suppose.
Would anyone have remapped a non-paused "o" to some other function? That might need some announcement to go with the change.
Hope that doesn't sound too negative - more of a brain dump, really. I think it's worth doing, myself.

**Comment by AnotherCommander** [comment]
I think we can close this as an issue for now. The idea has merit and should probably be discussed somewhere with more visibility. I just want to be sure that if we do implement this, no gameplay elements will be sacrificed. @clintmoyer : Thanks for bringing this to our attention and feel free to start a topic on the forum if you feel it can be worth it. If it turns out that people have no issues with it, we can always enable it without side effects due to the simplicity of the implementation.
