### ISSUE TITLE
make fail ubuntu 18.04 WSL.

### ISSUE THREAD

**Issue by dreaddymck** [OoliteProject/oolite#347]
[dreaddy@thing oolite] :( make -f Makefile
make -f GNUmakefile debug=yes strip=no
make[1]: Entering directory '/mnt/c/Users/dreaddy/Downloads/git/oolite'
GNUmakefile:1: /common.make: No such file or directory
GNUmakefile:450: /objc.make: No such file or directory
make[1]: *** No rule to make target '/objc.make'.  Stop.
make[1]: Leaving directory '/mnt/c/Users/dreaddy/Downloads/git/oolite'
Makefile:73: recipe for target 'debug' failed
make: *** [debug] Error 2

**Comment by AnotherCommander** [comment]
Did you install gnustep  / gnustep-make before running the make command? If yes, then there is a GNUstep.sh script that has to be run before using gnustep-make. I am not sure where it resides on Linux though. The GNUstep installation should take care of placing all the necessary files where they need to be so that you will not have to do this manually under normal circumstances,

Instructions for building from source in Linux are here: http://wiki.alioth.net/index.php/Running_Oolite-Linux#Building_Oolite-Linux_from_source 

Hope this helps, or we may have to wait for a Linux port dev to chime in.

**Comment by dreaddymck** [comment]
Eventually figured out  gnustep, but that exposed a number of unknown target/type errors.

Going to close this post anyways as this is an environment error.

**Comment by mwerle** [comment]
Heh, was a bit slow in replying. But in case anybody else is reading this after having the same issue:

http://www.gnustep.org/resources/documentation/User/GNUstep/gnustep-howto_4.html

Except in current Debian (Ubuntu?) the location is:

/usr/share/GNUstep/Makefiles/GNUstep.sh
