### ISSUE TITLE
ARM Mac build is broken.

### ISSUE THREAD

**Issue by MaddTheSane** [OoliteProject/oolite#360]
With Apple moving to their own ARM-based CPUs named Apple Silicon, I decided to see how well oolite would build. Turns out, there's some work that needs to be done:

* libjs needs to be updated to take advantage of the ARMv8/ARM64 architecture.
* the `ARCHS` flag in oolite-target.xcconfig needs to be updated to include `arm64`.
* Changes in Clang has made a lot of "Messaging unqualified id" warnings pop up all over the code.

**Comment by phkb** [comment]
When you say "libjs needs to be updated to take advantage of the ARM architecture", does the current libjs work at all? Does it work in some sub-optimal way?

**Comment by MaddTheSane** [comment]
It fails to build.

**Comment by phkb** [comment]
Ah, thanks.

**Comment by AnotherCommander** [comment]
It pains me to have to say this, but I think that Mac support is about to end. 

For starters, we do not currently have any Mac maintainer. For the last few years, any Mac related bug fix or feature entered in the core has been purely by blind debugging / blind coding from the remaining maintainers and hoping that it works (and so far, thankfully, it has). Obviously, there will come a time where this will fail. When it does, we will not be able to fix Mac code properly.

Secondly, Apple has distanced itself from gaming in the course of the last years. They abandoned OpenGL, they change their core architecture whenever they see fit and they change their development environment too frequently, with sweeping changes across the board. This last switch to ARM-based CPU is such a change.

For us, this means that without a dedicated maintainer, Apple support will simply not continue. We will take it as far as we can with the resources and the knowledge the current team has and, when those resources stop being adequate, we will stop providing support. There is simply nothing else we can do.

Even if we did have an Apple port maintainer, in this particular case we would have to take some serious decisions. Updating libjs is out of the question. The amount of OXPs written for the currently used Spidermonkey version simply forbids that, unless we are OK with breaking something like three to four hundred OXPs or so.  Also, building a new Spidermonkey for Windows is not a task I am willing to undertake. I did it once and it was more than enough. So, assuming there was a Mac maintainer here, we would need to discuss whether we drop support for Mac or for Windows, since the current JS and the new Apple compatible JS are mutually exclusive for us. 

I know it is hard. It is also painful, because Oolite started on a Mac. But we are at a point where we seriously need  to consider our future platform support options. In  a few months, building Oolite for Mac in its current form will not be possible at all.

**Comment by Garryck** [comment]
Sounds like it might be worth putting out an All Points Bulletin on the
forums, asking for anyone with experience coding on Macs, maybe?

**Comment by HiranChaudhuri** [comment]
Indeed what AnotherCommander stated is true. If you can find people willing to contribute please do so.

**Comment by HiranChaudhuri** [comment]
It sounds like there is no more communication in this matter. Please reopen if need be.

**Comment by keaaw** [comment]
I can poke around (I'm Bogatyr on the forums) to see if anything can be done.

**Comment by mcarans** [comment]
The author of another framework like GNUStep (Mulle-Objc) told me that "An unqualified id is no problem. It just a warning you can squelch with a #pragma."
