### ISSUE TITLE
Mouse Yaw/Pitch

### ISSUE THREAD

**Issue by dreaddymck** [OoliteProject/oolite#364]
The following is a diff between code base

https://github.com/dreaddymck/dump/blob/master/oolite-custom-control-git-diff.txt

It inverts the pitch/yaw, overrides the control key and max FOV.

Question: Is it possible to accomplish this with just an addon script?

**Comment by phkb** [comment]
It would probably be better to make each suggested change (inverting pitch/yaw, control key override and max FOV setting) a separate issue/diff so the pros/cons of each can be discussed independently.

As for making it OXP-able, I'd say the answer is probably no. At best I think making the settings switchable via settings is more possible. But I'm happy to be led by more experienced contributors.

**Comment by AnotherCommander** [comment]
This is not really an issue, should be a PR, but anyway to answer the question:

Not all of is can be accomplished by script. Only the pitch inversion is possible and there is already an OXP that does that. The other two changes are achievable only in code.

Since this is not an issue, if the above answers the question in a satisfactory , I will proceed to close this issue shortly.

**Comment by dreaddymck** [comment]
Thank you
