### ISSUE TITLE
Oolite speech synthesis troubleshooting

### ISSUE THREAD

**Issue by YuGiOhJCJ** [OoliteProject/oolite#367]
Hello,

I am on [Slackware](http://www.slackware.com/) 14.2 (64-bit).
I downloaded and installed [Oolite 1.90 for 64-bit Linux](https://github.com/OoliteProject/oolite/releases/download/1.90/oolite-1.90.linux-x86_64.tgz).
The game runs fine except for speech synthesis.
Indeed, in the Game Options menu, the Spoken Messages, Voice, and Gender items are disabled (I cannot select them).

I guess that there is a problem with the provided `libespeak` library.
So I tried:
```
$ cd ~/GNUstep/Applications/Oolite/oolite-deps/lib
$ cp -p libespeak.so.1 libespeak.so.1.portaudio
$ cp -p libespeak.so.1.pulseaudio libespeak.so.1
$ ~/GNUstep/Applications/Oolite/oolite
```
But the problem is still there.
So I tried:
```
$ cd ~/GNUstep/Applications/Oolite/oolite-deps/lib
$ mv libespeak.so.1 libespeak.so.1.oolite
$ ~/GNUstep/Applications/Oolite/oolite
```
But there is a new problem:
```
$ ~/GNUstep/Applications/Oolite/oolite
Can't read data file: '/home/yugiohjcj/GNUstep/Applications/Oolite/oolite.app/Resources//espeak-data/intonations'
Failed to load espeak-data
AL lib: (EE) alc_cleanup: 1 device not closed

Erk. It looks like Oolite died with an error. When making an error
report, please copy + paste the log above into the report.

(Press Ctrl-C to continue)
```

On my OS, espeak 1.48.04 is installed and is working:
```
$ espeak 
abc
```
I heard "abc" in my headphones.

What else can I do to get speech synthesis please?

Thank you.
Best regards.

**Comment by KonstantinosSykas** [comment]
Hi @YuGiOhJCJ ,
I believe that your system's `libespeak` looks for a different `espeak-data` folder structure, that is not compatible with the one we deliver for the older Oolite library. Assuming that the Oolite `libespeak` is renamed (as you described above), thus enabling your system's `libespeak` to kick in, please do the following.

Edit the script file 
`/home/yugiohjcj/GNUstep/Applications/Oolite/oolite.app/oolite-wrapper`

and comment out the line
`export ESPEAK_DATA_PATH=${OOLITE_ROOT}/oolite.app/Resources/`

The update line should look like this 
`# export ESPEAK_DATA_PATH=${OOLITE_ROOT}/oolite.app/Resources/`

If I'm right, this will allow your system's `libespeak` to look into your system's `espeak-data` folder.
Let me know if this addresses the issue.

**Comment by YuGiOhJCJ** [comment]
I edited the `oolite-wrapper` file and now I can use my system's `libespeak`.
So, it fixes the new problem (`Erk. It looks like Oolite died with an error.`) but it does not fix the old problem (in the Game Options menu, the Spoken Messages, Voice, and Gender items are disabled).
The speech synthesis is still not working (assuming that docking requests and other in-game actions are supposed to generate voices in my headphones).
Note: I forgot to say that the menu music and the menu sounds are working fine.

**Comment by KonstantinosSykas** [comment]
Thank you for your patience @YuGiOhJCJ . 🙇‍♂️ 

Are you checking the _proper_ "Game Options" menu? ❔❕❔ 
💡Let me clarify that the "Spoken Messages" settings are always disabled in the "Game Options" menu presented in the rotating Cobra opening screen. To check/configure the "Spoken Messages" settings you either do it in-game when docked (you press F2 and then select "Game Options") or while being in-flight (first press "p" to pause the game, then press "F2" and then select "Game Options").💡
If during this case you were only checking the starting screen Game Options menu 😱, please, revert all changes 😳, 

- by first restoring the `portaudio `version of Oolite's `libespeak ` and 
- then by uncommenting the `oolite-wrapper` `ESPEAK_DATA_PATH` code line 

and then check again the `Spoken Messages` status in the _proper_ in-game "Game Options" screen.

Having confirmed this, and assuming that

- so far you were looking into the _proper_ in-game "Game Options" menu, 
- the "Spoken Messages" settings are still greyed out 😕, and 
- you have performed changes so that your system's libespeak is used,

please, proceed to the following troubleshooting action. 
```
# Warning: The next code line is long. Ensure you have copied the entire code line!
$ mv /home/yugiohjcj/GNUstep/Applications/Oolite/oolite-deps/lib/libportaudio.so.2 /home/yugiohjcj/GNUstep/Applications/Oolite/oolite-deps/lib/libportaudio.so.2.oolite 
$ /home/yugiohjcj/GNUstep/Applications/Oolite/oolite
```
This is to let your system's `libespeak` use your system's libportaudio.

If this doesn't work, please, post here the contents of `/home/yugiohjcj/.Oolite/Logs/Latest.log` file. 
Furthermore, I would highly appreciate if you could locate your system's `libespeak.so.1` and execute `ldd` to get its dependencies.
For example, in my system it goes like this:
```
terrastorage@Hermes:~$ cd / 
terrastorage@Hermes:/$ find . -name libespeak.so.1 -print 2> /dev/null
./usr/lib/x86_64-linux-gnu/libespeak.so.1
./opt/Oolite/oolite-deps/lib/libespeak.so.1
terrastorage@Hermes:/$ ldd /usr/lib/x86_64-linux-gnu/libespeak.so.1
        linux-vdso.so.1 =>  (0x00007ffd01ca6000)
        libpulse.so.0 => /usr/lib/x86_64-linux-gnu/libpulse.so.0 (0x00007f681bf72000)
        libpulse-simple.so.0 => /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0 (0x00007f681bd6e000)
        libportaudio.so.2 => /usr/lib/x86_64-linux-gnu/libportaudio.so.2 (0x00007f681bb3f000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f681b921000)
        libsonic.so.0 => /usr/lib/x86_64-linux-gnu/libsonic.so.0 (0x00007f681b71c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f681b416000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f681b04d000)
...
# and many more, but in your response, please, post all dependencies!
...
terrastorage@Hermes:/$
```

I will be waiting for your feedback!

**Comment by YuGiOhJCJ** [comment]
Thanks a lot!
Indeed, I was in the wrong menu.
When I press F2 in-game, the `Spoken Messages` option is available and it is working!
I am now able to heard the spoken messages.
Problem fixed.

**Comment by KonstantinosSykas** [comment]
Excellent news! 🥳 🥳 🥳 

@YuGiOhJCJ ensure that you use the Oolite `libespeak` (the portaudio version) library and that you restore the code line in `oolite-wrapper` (the one you commented out during our troubleshooting session). 
This will ensure that you will listen to the speech synthesis as we have configured it for the game! 

Fly Safe and Dock Straight Commander!
