### ISSUE TITLE
Bug Report: equipment_by_ship.oxz

### ISSUE THREAD

**Issue by MosayIC** [OoliteProject/oolite#370]
This oxp was causing my game to crash.

When I filtered between folders, this one crashed my game every time.

System: windows 10

**Comment by AnotherCommander** [comment]
Can you please post the Latest.log following a crash? Thanks.

**Comment by MosayIC** [comment]
I don't know how do do that, but if you'll tell me I can recreate the problem.

**Comment by AnotherCommander** [comment]
Get the game to crash, then look for the file Latest.log inside <Your Oolite Install Folder>\oolite,app\Logs, and then post its contents here.

**Comment by MosayIC** [comment]
[Latest.log](https://github.com/OoliteProject/oolite/files/5357065/Latest.log)

13:53:28.019 [startup.exception]: ***** Unhandled exception during startup: NSInvalidArgumentException (Tried to add nil value for key 'EQ_WEAPON_TWIN_PLASMA_CANNON' to dictionary).

**Comment by AnotherCommander** [comment]
Confirmed. 1.88 does not throw an exception, but 1.90 does. Until this is fixed properly, the quick fix is to open the OXP's Config/equipment.plist, find this:

/* next item was a test item */
	(
		2, 2000, "Twin Plasma Cannon",
		"EQ_WEAPON_TWIN_PLASMA_CANNON",
		"Basic cannon delivering charged plasma bursts at sublight speed."
	),

and change it to this:

/* next item was a test item */
	(
		2, 2000, "Twin Plasma Cannon",
		"EQ_WEAPON_TWIN_PLASMA_CANNON",
		"Basic cannon delivering charged plasma bursts at sublight speed.",{}       // this is ths changed line	
       ),

**Comment by MosayIC** [comment]
Done and done. It works now. Thanks.

**Comment by AnotherCommander** [comment]
Just a note to say that the bug should now be properly fixed in commit 6b45ec2. The equipment_by_ship_class OXP and any other OXPs that contain equipment definitions without an extra info dictionary should no longer cause an exception.

A Windows 64 bit fixed game executable can be downloaded from [here]( https://drive.google.com/file/d/10xEtdzmIep39nSBzDKhcZhPFVSP3vN1R/view?usp=sharing).
(VirusTotal report [here]( https://www.virustotal.com/gui/file/ccf87f3fb6f03835d9cd4a4826eee95b87a973c5b5bfaa3cc33e1b5bcc23e51c/detection)).
