### ISSUE TITLE
Bug report: Xbox one controller

### ISSUE THREAD

**Issue by MosayIC** [OoliteProject/oolite#371]
The Xbox one controller registers it's trigger functions as z axis, and Oolite doesn't pick up on it. I'm not sure ow to recreate this for you. Suggestions?

**Comment by AnotherCommander** [comment]
Which function(s) are you trying to assign to the triggers when setting up the controller?

**Comment by MosayIC** [comment]
Fine control and lock missile

**Comment by MosayIC** [comment]
On top of this issue, I get a desirable effect when I assign accelerate and decel to the xaxis2 (left stuck), but I lose keyboard control of my speed. How can I fix this?

Also, did my allied in the fight fire on me because of my joystick? Did I imagine the correlation?

**Comment by AnotherCommander** [comment]
Fine control, missile arm and missile fire are all functions mappable to buttons only. This is why the triggers don't work.

If you map acceleration and deceleration to stick, then keyboard acceleration controls won't work. You either use the stick or the keyboard, not both. The only way to fix this is by directly modifying the game code, but it is really like that by design.

Allies firing on you is completely independent from the joystick,.

**Comment by MosayIC** [comment]
So would modifying the game code require me to download the source code and recompile when done?

**Comment by AnotherCommander** [comment]
Yes, that is correct.

**Comment by MosayIC** [comment]
And is the code listed here on front page the source?

Also, as to keep this brief, do you have a recommended compiler?

**Comment by AnotherCommander** [comment]
Full compiling instructions for Windows, including how to obtain the code, as well as a ready-made development environment that you can download and use right away can be found here: http://www.aegidian.org/bb/viewtopic.php?f=8&t=5943

**Comment by MosayIC** [comment]
Thank you.
