### ISSUE TITLE
Unassigned F11 key in MyOpenGLView.m

### ISSUE THREAD

**Issue by STyx2909** [OoliteProject/oolite#379]
I noticed F11 is not assigned in this file (ending at F10 and then later F12).
 It is a mistake? or is it due, as it is pointed in the BB forum from archives, this is because of specific Windows behavior?

> _And I almost forgot: pressing f11 will cycle through all display resolutions windows says are available: pressing f11 a few times should eventually take you to a usable display resolution.
However, shift-f11 should cycle through resolutions in the opposite direction. Instead of tapping f11 a gazillion times, tapping shift-f11 once might well have saved the day...

> Something to highlight in the documentation for 1.75, methinks!_ 

Reported here also: http://aegidian.org/bb/viewtopic.php?f=3&p=273511#p273511

**Comment by AnotherCommander** [comment]
It is just not needed at this time. The quote in the post above refers to an older version of the game and resolution switching is done differently now, eliminating the need for F11. If it is required for a specific future game functionality, we can re-enable it.

If this response is considered sufficient, please advise so that we can close the issue.

**Comment by STyx2909** [comment]
Yep, you can close it. Though, we must point to users this key cannot be mapped.
